# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: lcXpOpk1r932mXU7
  pool: 5


  pool: 5

development:
  <<: *default
  database: feelhome_development

test:
  <<: *default
  database: feelhome_test

production:
  primary: &primary_production
    <<: *default
    database: feelhome_production
    username: feelhome
    password: <%= ENV["FEELHOME_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: feelhome_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: feelhome_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: feelhome_production_cable
    migrations_paths: db/cable_migrate
